# Generated by Django 5.2.1 on 2025-06-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadsecSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source_subnets', models.JSONField(blank=True, default=list, help_text='List of source subnets allowed to use this secret', verbose_name='Source Subnets')),
                ('tls_key', models.TextField(verbose_name='TLS Key')),
                ('tls_cert', models.TextField(verbose_name='TLS Cert')),
            ],
            options={
                'verbose_name': 'RadSec Source',
                'verbose_name_plural': 'RadSec Sources',
                'db_table': 'radec_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadsecDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('radsec_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radsec.radsecsource')),
            ],
            options={
                'verbose_name': 'RadSec Destination',
                'verbose_name_plural': 'RadSec Destinations',
                'db_table': 'radsec_destinations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['radsec_source'], name='rad_sec_source_idx')],
            },
        ),
    ]
