# Generated by Django 5.2.1 on 2025-05-17 08:12

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('vendor_id', models.PositiveIntegerField(unique=True, verbose_name='Vendor ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'nas_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nas.nasgroup', verbose_name='Parent Group')),
            ],
            options={
                'verbose_name': 'NAS Group',
                'verbose_name_plural': 'NAS Groups',
                'db_table': 'nas_nas_group',
            },
        ),
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NAS Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('coa_enabled', models.BooleanField(default=False, verbose_name='CoA Enabled')),
                ('coa_port', models.PositiveIntegerField(default=3799, verbose_name='CoA Port')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('groups', models.ManyToManyField(blank=True, related_name='nas_devices', to='nas.nasgroup', verbose_name='NAS Groups')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nas_devices', to='nas.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'NAS',
                'verbose_name_plural': 'NAS Devices',
                'db_table': 'nas_nas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Attribute Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('attribute_id', models.PositiveIntegerField(verbose_name='Attribute ID')),
                ('attribute_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('ipaddr', 'IP Address'), ('date', 'Date'), ('octets', 'Octets')], max_length=20, verbose_name='Attribute Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='nas.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Attribute',
                'verbose_name_plural': 'Vendor Attributes',
                'db_table': 'nas_vendor_attribute',
                'ordering': ['vendor', 'attribute_id'],
                'unique_together': {('vendor', 'attribute_id')},
            },
        ),
    ]
