# Generated by Django 5.2.1 on 2025-05-17 11:15

from django.db import migrations, models
import django.db.models.deletion


def set_default_secret(apps, schema_editor):
    """
    Set the default secret for all NAS devices.
    """
    # Get the models
    Secret = apps.get_model('radius', 'Secret')
    Nas = apps.get_model('nas', 'Nas')

    # Get the default secret
    default_secret = Secret.objects.get(name="OpenRDX")

    # Update all NAS devices to use the default secret
    Nas.objects.update(secret=default_secret)


def reverse_set_default_secret(apps, schema_editor):
    """
    Remove the secret from all NAS devices.
    """
    # Get the model
    Nas = apps.get_model('nas', 'Nas')

    # Remove the secret from all NAS devices
    Nas.objects.update(secret=None)


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_create_default_nas_groups_and_vendors'),
        ('radius', '0003_create_secret_model_and_default_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='secret',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='nas_devices',
                to='radius.secret',
                verbose_name='Secret'
            ),
        ),
        migrations.RunPython(
            set_default_secret,
            reverse_set_default_secret
        ),
    ]
