# Generated by Django 5.2.1 on 2025-05-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0003_add_secret_to_nas'),
        ('shared', '0003_alter_timezone_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.timezone'),
        ),
    ]
