from rest_framework import serializers
from django.utils import timezone
from datetime import timedelta
from .models import ApiKey


class ApiKeySerializer(serializers.ModelSerializer):
    """
    Serializer for the ApiKey model.
    """
    created_by_email = serializers.SerializerMethodField()
    is_expired = serializers.SerializerMethodField()
    days_until_expiry = serializers.SerializerMethodField()

    class Meta:
        model = ApiKey
        fields = [
            'id', 'name', 'key', 'expires_at', 'created_by', 'created_by_email',
            'is_active', 'last_used_at', 'created_at', 'updated_at',
            'is_expired', 'days_until_expiry'
        ]
        read_only_fields = [
            'id', 'key', 'created_by', 'created_at', 'updated_at',
            'last_used_at', 'is_expired', 'days_until_expiry'
        ]

    def get_created_by_email(self, obj):
        """Return the email of the user who created the API key."""
        return obj.created_by.email if obj.created_by else None

    def get_is_expired(self, obj):
        """Return whether the API key has expired."""
        return obj.is_expired()

    def get_days_until_expiry(self, obj):
        """Return the number of days until the API key expires."""
        if obj.is_expired():
            return 0
        delta = obj.expires_at - timezone.now()
        return max(0, delta.days)


class ApiKeyCreateSerializer(serializers.Serializer):
    """
    Serializer for creating a new API key.
    Only requires validity_days, the key will be generated by the view.
    """
    name = serializers.CharField(
        max_length=255,
        help_text="A descriptive name for this API key"
    )
    validity_days = serializers.IntegerField(
        min_value=1,
        max_value=3650,  # 10 years in days
        help_text="Number of days the API key should be valid (1 day to 10 years)"
    )

    def validate_validity_days(self, value):
        """Validate that validity_days is within the allowed range."""
        if value < 1 or value > 3650:
            raise serializers.ValidationError("Validity must be between 1 day and 10 years (3650 days).")
        return value

