apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-backend
  namespace: openrdx
  labels:
    app: oss-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oss-backend
  template:
    metadata:
      labels:
        app: oss-backend
    spec:
      containers:
      - name: oss-backend
        image: openrdx/oss-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/openrdx"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: oss-backend
  namespace: openrdx
spec:
  selector:
    app: oss-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 