# Generated by Django 5.2.1 on 2025-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0006_nas_nas_vendor_idx_nas_nas_ip_idx_and_more'),
        ('radius', '0003_create_secret_model_and_default_secret'),
        ('users', '0014_user_allow_any_nas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='rad_sec',
        ),
        migrations.AddIndex(
            model_name='radiusattribute',
            index=models.Index(fields=['vendor_id'], name='rad_att_vendor_id'),
        ),
        migrations.AddIndex(
            model_name='radiusattribute',
            index=models.Index(fields=['group'], name='rd_att_group_idx'),
        ),
        migrations.AddIndex(
            model_name='usernasrelationship',
            index=models.Index(fields=['user'], name='user_to_nas_idx'),
        ),
    ]
