# Generated by Django 5.2.1 on 2025-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0003_alter_adminuser_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['email'], name='admin_email_idx'),
        ),
    ]
