# Generated by Django 5.2.1 on 2025-05-17 10:30

from django.db import migrations


def create_default_user_groups(apps, schema_editor):
    """
    Create default user groups.
    """
    # Get the model
    UserGroup = apps.get_model('users', 'UserGroup')

    # Create NOC group
    noc, created = UserGroup.objects.get_or_create(
        name="NOC",
        defaults={
            'description': "Network Operations Center staff",
            'lft': 1,
            'rght': 2,
            'tree_id': 1,
            'level': 0
        }
    )

    # Create Subscribers parent group
    subscribers, created = UserGroup.objects.get_or_create(
        name="Subscribers",
        defaults={
            'description': "All subscribers",
            'lft': 1,
            'rght': 8,  # 2 * (number of children + 1)
            'tree_id': 2,
            'level': 0
        }
    )

    # Create subscriber subgroups
    fwa_subscribers, created = UserGroup.objects.get_or_create(
        name="FWA Subscribers",
        defaults={
            'description': "Fixed Wireless Access subscribers",
            'parent': subscribers,
            'lft': 2,
            'rght': 3,
            'tree_id': 2,
            'level': 1
        }
    )

    gpon_subscribers, created = UserGroup.objects.get_or_create(
        name="GPON Subscribers",
        defaults={
            'description': "Gigabit Passive Optical Network subscribers",
            'parent': subscribers,
            'lft': 4,
            'rght': 5,
            'tree_id': 2,
            'level': 1
        }
    )

    dsl_subscribers, created = UserGroup.objects.get_or_create(
        name="DSL Subscribers",
        defaults={
            'description': "Digital Subscriber Line subscribers",
            'parent': subscribers,
            'lft': 6,
            'rght': 7,
            'tree_id': 2,
            'level': 1
        }
    )

    # Create Installers group
    installers, created = UserGroup.objects.get_or_create(
        name="Installers",
        defaults={
            'description': "Field technicians and installers",
            'lft': 1,
            'rght': 2,
            'tree_id': 3,
            'level': 0
        }
    )


def reverse_default_user_groups(apps, schema_editor):
    """
    Reverse the creation of default user groups.
    """
    # Get the model
    UserGroup = apps.get_model('users', 'UserGroup')

    # Delete all default user groups
    UserGroup.objects.filter(name="NOC").delete()
    UserGroup.objects.filter(name="Subscribers").delete()
    UserGroup.objects.filter(name="FWA Subscribers").delete()
    UserGroup.objects.filter(name="GPON Subscribers").delete()
    UserGroup.objects.filter(name="DSL Subscribers").delete()
    UserGroup.objects.filter(name="Installers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_user_groups,
            reverse_default_user_groups
        ),
    ]
