# Generated by Django 5.2.1 on 2025-05-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_user_groups'),
        ('users', '0002_user_identifier'),
    ]

    operations = [
    ]
