# Generated by Django 5.2.1 on 2025-05-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250519_0022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='user_groups',
        ),
        migrations.AlterModelTable(
            name='useridentifier',
            table='user_identifiers',
        ),
        migrations.AlterModelTable(
            name='useridentifiertype',
            table='user_identifier_types',
        ),
    ]
