# Generated by Django 5.2.1 on 2025-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_table_alter_usergroup_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='External ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['external_id'], name='users_externa_aa6389_idx'),
        ),
    ]
