# Generated by Django 5.2.1 on 2025-05-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0003_create_secret_model_and_default_secret'),
        ('users', '0006_useridentifier_plain_password_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useridentifier',
            index=models.Index(fields=['value', 'identifier_type'], name='user_identi_value_c3fc9f_idx'),
        ),
    ]
