# Generated by Django 5.2.1 on 2025-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useridentifier_user_identi_value_c3fc9f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
    ]
