# Generated by Django 5.2.1 on 2025-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifiertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
