# Generated by Django 5.2.1 on 2025-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useridentifiertype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifier',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
