# Generated by Django 5.2.1 on 2025-05-21 01:08

from django.db import migrations, models

def create_default_identifier_types(apps, schema_editor):
    UserIdentifierType = apps.get_model('users', 'UserIdentifierType')
    default_types = [
        {
            'name': 'Username/Password',
            'description': 'Standard username and password authentication',
            'code': 'PWD'
        },
        {
            'name': 'MAC',
            'description': 'MAC address based authentication',
            'code': 'MAC'
        },
        {
            'name': 'IMSI',
            'description': 'International Mobile Subscriber Identity',
            'code': 'SIM'
        },
        {
            'name': 'Serial',
            'description': 'Serial number based authentication',
            'code': 'SN'
        }
    ]
    for type_data in default_types:
        UserIdentifierType.objects.get_or_create(
            name=type_data['name'],
            code=type_data['code'],
            defaults={'description': type_data['description']}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_useridentifier_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentifiertype',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='useridentifiertype',
            index=models.Index(fields=['code'], name='user_identi_code_2c5d01_idx'),
        ),
        migrations.RunPython(create_default_identifier_types),

    ]
