# Generated by Django 5.2.1 on 2025-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useridentifiernasauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='allow_any_nas',
            field=models.BooleanField(default=False, verbose_name='Allow All NAS'),
        ),
    ]
