# Generated by Django 5.2.1 on 2025-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usergroup_allow_any_nas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_any_nas',
            field=models.BooleanField(null=True, verbose_name='Allow All NAS'),
        ),
    ]
