# Generated by Django 5.2.1 on 2025-05-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_load_timezones'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timezone',
            table='timezones',
        ),
    ]
